USE [master]
GO
/****** Object:  Database [TaylorWessing]    Script Date: 14/11/2024 15:43:23 ******/
CREATE DATABASE [TaylorWessing]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'TaylorWessing', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TaylorWessing.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'TaylorWessing_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\TaylorWessing_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [TaylorWessing] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [TaylorWessing].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [TaylorWessing] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [TaylorWessing] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [TaylorWessing] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [TaylorWessing] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [TaylorWessing] SET ARITHABORT OFF 
GO
ALTER DATABASE [TaylorWessing] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [TaylorWessing] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [TaylorWessing] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [TaylorWessing] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [TaylorWessing] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [TaylorWessing] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [TaylorWessing] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [TaylorWessing] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [TaylorWessing] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [TaylorWessing] SET  DISABLE_BROKER 
GO
ALTER DATABASE [TaylorWessing] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [TaylorWessing] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [TaylorWessing] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [TaylorWessing] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [TaylorWessing] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [TaylorWessing] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [TaylorWessing] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [TaylorWessing] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [TaylorWessing] SET  MULTI_USER 
GO
ALTER DATABASE [TaylorWessing] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [TaylorWessing] SET DB_CHAINING OFF 
GO
ALTER DATABASE [TaylorWessing] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [TaylorWessing] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [TaylorWessing] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [TaylorWessing] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [TaylorWessing] SET QUERY_STORE = ON
GO
ALTER DATABASE [TaylorWessing] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [TaylorWessing]
GO
/****** Object:  Table [dbo].[Client]    Script Date: 14/11/2024 15:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Client](
	[ClientId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[EmailId] [nvarchar](100) NULL,
	[Phone] [nvarchar](100) NULL,
	[DateAdded] [datetime] NULL,
 CONSTRAINT [PK_Client] PRIMARY KEY CLUSTERED 
(
	[ClientId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Matter]    Script Date: 14/11/2024 15:43:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Matter](
	[MatterId] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[DateCreated] [datetime] NULL,
	[ClientId] [int] NOT NULL,
 CONSTRAINT [PK_Matter] PRIMARY KEY CLUSTERED 
(
	[MatterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Client] ADD  CONSTRAINT [DF_Client_DateAdded]  DEFAULT (getdate()) FOR [DateAdded]
GO
ALTER TABLE [dbo].[Matter] ADD  CONSTRAINT [DF_Matter_DateCreated]  DEFAULT (getdate()) FOR [DateCreated]
GO
ALTER TABLE [dbo].[Matter]  WITH CHECK ADD  CONSTRAINT [FK_Matter_Client] FOREIGN KEY([ClientId])
REFERENCES [dbo].[Client] ([ClientId])
GO
ALTER TABLE [dbo].[Matter] CHECK CONSTRAINT [FK_Matter_Client]
GO
USE [master]
GO
ALTER DATABASE [TaylorWessing] SET  READ_WRITE 
GO
